sudo: false
git:
  depth: 1

language: node_js
node_js:
  - '4'
  - '5'
  - stable

matrix:
  fast_finish: true

install:
  - npm install -g yeoman gulp bower
  - npm install
  - npm link

before_script:
  # For protractor tests
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test